services:
  tms:
    image: tms:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      tms-db:
        condition: service_healthy
    environment:
      - SERVER_PORT= 5001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tms-db/dev_db

  tms-db:
    image: postgres:17.1
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "dev_db" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data: